name: Run and Test
on: push

jobs:
  TestAndRun:
    name: Unit test then run
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Unit Test
        run: |
          npm install
          npm run test
          npm run build
          npm run prod


